version: '3.3'
services:
  search_engine_db:
    image: mongo:${DB_VERSION}
    volumes:
      - search_engine_db:/data/db
    networks:
      back_net:
        aliases:
          - se_crawler_db
      front_net:
        aliases:
          - se_ui_db

  search_engine_ui:
    image: ${DH_USERNAME}/se_ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    environment:
      - MONGO=se_ui_db
      - MONGO_PORT=27017
    networks:
      - front_net

  search_engine_crawler:
    image: ${DH_USERNAME}/se_crawler:${CRAWLER_VERSION}
    environment:
      - MONGO=se_crawler_db
      - MONGO_PORT=27017
      - RMQ_HOST=search_engine_rmq
      - RMQ_QUEUE=se_queue
      - RMQ_USERNAME=${RMQ_USER}
      - RMQ_PASSWORD=${RMQ_PASS}
      - CHECK_INTERVAL=300
      - EXCLUDE_URLS=.*github.com
      - URL=https://vitkhab.github.io/search_engine_test_site/
    networks:
      - back_net

  search_engine_rmq:
    image: rabbitmq:${RMQ_VERSION}
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASS}
    networks:
      - back_net

volumes:
  search_engine_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: "10.0.2.0/24"
  front_net:
    ipam:
      config:
        - subnet: "10.0.1.0/24"
