---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: search-engine
    component: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
      component: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: search-engine
        component: mongo
    spec:
      containers:
      - image: mongo:3.2
        name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: search-engine
    component: mongo
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: search-engine
    component: mongo
