---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq
  labels:
    app: search-engine
    component: rmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
      component: rmq
  template:
    metadata:
      name: rmq
      labels:
        app: search-engine
        component: rmq
    spec:
      containers:
      - image: rabbitmq:3.8.9-alpine
        name: rmq
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: rmquser
        - name: RABBITMQ_DEFAULT_PASS
          value: rmqpassword

---
apiVersion: v1
kind: Service
metadata:
  name: rmq
  labels:
    app: search-engine
    component: rmq
spec:
  ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
    app: search-engine
    component: rmq
