crawler:
  image:
    repository: isieiam/se_crawler
    tag: "1.0"

rabbitmq:
  auth:
    username: rmquser
    password: rmqpassword
    erlangCookie: "12345678901234567890123456789011"
  persistence:
    enabled: false
#  podLabels:
#    app: search-engine
#    component: rmq


mongodb:
  usePassword: false
#  labels:
#    app: search-engine
#    component: db
#  podLabels:
#    app: search-engine
#    component: db


ui:
  image:
    repository: isieiam/se_ui
    tag: "1.0"
  service:
    externalPort: 8000
  ingress:
    host: 84.201.173.11.nip.io


