---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: search-engine
    component: crawler
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      labels:
        app: search-engine
        component: crawler
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: crawler
        env:
        - name: MONGO
          value: {{  .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
        - name: MONGO_PORT
          value: {{  .Values.databasePort | default "27017" | quote }}
        - name: RMQ_HOST
          value: {{  .Values.rmqHost | default (printf "%s-rabbitmq" .Release.Name) }}
        - name: RMQ_QUEUE
          value: se_queue
        - name: RMQ_USERNAME
          value: rmquser
        - name: RMQ_PASSWORD
          value: rmqpassword
        - name: CHECK_INTERVAL
          value: '300'
        - name: EXCLUDE_URLS
          value: '.*github.com'
        - name: URL
          value: 'https://vitkhab.github.io/search_engine_test_site/'
